language: haskell
ghc: "7.10"

env:
 - CABALVER=1.22 GHCVER=7.10.1

before_install:
 #- travis_retry sudo add-apt-repository -y ppa:hvr/ghc
 #- travis_retry sudo apt-get update
 #- travis_retry sudo apt-get install cabal-install-$CABALVER ghc-$GHCVER # see note about happy/alex
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 
addons:
  apt:
    sources: 
      - hvr-ghc
    packages:
      - cabal-install-1.22
      - ghc-7.10.1


install:
 - cabal --version
 - echo "$(ghc --version) [$(ghc --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - travis_retry cabal update
 - cabal install --only-dependencies --enable-tests --enable-benchmarks

script:
 - if [ -f configure.ac ]; then autoreconf -i; fi
 - cabal configure --enable-tests --enable-benchmarks -v2
 - cabal build
 - cabal test
 - cabal check
 - cabal sdist
 - SRC_TGZ=$(cabal info . | awk '{print $2;exit}').tar.gz &&
   (cd dist && cabal install --force-reinstalls "$SRC_TGZ")

notifications:
  email: false
